# Generated by Django 4.1.7 on 2023-03-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_img',
            field=models.ImageField(default='default.png', upload_to='img/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='default.png', upload_to='img/%Y/%m/%d'),
        ),
    ]
